import Head from 'next/head'
import loginPage from "../../components/pages/loginPage"
import registerPage from "../../components/pages/registerPage";
import forgotPassword from "../../components/pages/forgotPassword";

import {selectAuthPage } from "../../redux/authSlice";
import { useSelector } from "react-redux";

export default function Auth() {

    const authPage = useSelector(selectAuthPage);

    const renderLoginPage = () => { return loginPage(); }
    const renderRegPage = () => { return registerPage(); }
    const renderForgotPage = () => { return forgotPassword(); }

    const frameRender = () => {
        if(authPage == "login") {
            return renderLoginPage()
        } else if(authPage == "register") {
            return renderRegPage()
        } else {
            return renderForgotPage()
        }
    }

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {frameRender()}
        </div>
    )
}
